export const GET_SCOOTERS_LOADING = "GET_SCOOTERS_LOADING";
export const GET_SCOOTERS_SUCCESS = "GET_SCOOTERS_SUCCESS";
export const GET_SCOOTERS_ERROR = "GET_SCOOTERS_ERROR";

export const GET_SCOOTER_BY_ID_LOADING = "GET_SCOOTER_BY_ID_LOADING";
export const GET_SCOOTER_BY_ID_SUCCESS = "GET_SCOOTER_BY_ID_SUCCESS";
export const GET_SCOOTER_BY_ID_ERROR = "GET_SCOOTER_BY_ID_ERROR";

export const ADD_SCOOTER_LOADING = "ADD_SCOOTER_LOADING";
export const ADD_SCOOTER_SUCCESS = "ADD_SCOOTER_SUCCESS";
export const ADD_SCOOTER_ERROR = "ADD_SCOOTER_ERROR";

export const DELETE_SCOOTER_LOADING = "DELETE_SCOOTER_LOADING";
export const DELETE_SCOOTER_SUCCESS = "DELETE_SCOOTER_SUCCESS";
export const DELETE_SCOOTER_ERROR = "DELETE_SCOOTER_ERROR";

export const EDIT_SCOOTER_LOADING = "EDIT_SCOOTER_LOADING";
export const EDIT_SCOOTER_SUCCESS = "EDIT_SCOOTER_SUCCESS";
export const EDIT_SCOOTER_ERROR = "EDIT_SCOOTER_ERROR";

export const CLEAR_SUCCESS_SCOOTER = "CLEAR_SUCCESS_SCOOTER";
export const CLEAR_ERRORS_SCOOTER = "CLEAR_ERRORS_SCOOTER";
